name: CI Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display Welcome Message
        run: echo "Pipeline Started for OST Practical 4!"

      - name: Display Current Directory
        run: pwd

      - name: List Project Files
        run: ls -la

      - name: Display Completion Message
        run: echo "Pipeline Completed Successfully!"
